- id: doi:10.3389/fpsyg.2022.1059823
  image: https://www.frontiersin.org/files/Articles/1059823/fpsyg-13-1059823-HTML-r3/image_m/fpsyg-13-1059823-g001.jpg

- title: Can Syntactic Log-Odds Ratio Predict Acceptability and Satiation?
  authors:
    - Jiayi Lu
    - Jonathan Merchan
    - Lian Wang
    - Judith Degen
  publisher: Proceedings of the Society for Computation in Linguistics
  date: 2024-06-01
  link: https://aclanthology.org/2024.scil-1.2/
  image: https://github.com/lu-jiayi/homepage/blob/master/scil-png.png

- title: Syntactic satiation is driven by speaker-specific adaptation
  authors:
    - Jiayi Lu
    - Daniel Lassiter
    - Judith Degen
  publisher: Proceedings of the Annual Meeting of the Cognitive Science Society
  date: 2021-06-01
  link: https://escholarship.org/uc/item/1dn4v3b4
  image: https://github.com/lu-jiayi/homepage/blob/master/adapt_png.png

- title: Satiation effects generalize across island types
  authors:
    - Jiayi Lu
    - Nicholas Wright
    - Judith Degen
  publisher: Proceedings of the Annual Meeting of the Cognitive Science Society
  date: 2022-06-01
  link: https://escholarship.org/uc/item/90j270js

- id: doi:10.5070/G60111425
  image: https://escholarship.org/content/qt33t7f9s4/glossapx-3-1-1425-g4.png

- id: doi:10.3389/fpsyg.2022.907823
  image: https://www.frontiersin.org/files/Articles/907823/fpsyg-13-907823-HTML-r1/image_m/fpsyg-13-907823-g003.jpg

- id: doi:10.1111/cogs.13383
  image: https://onlinelibrary.wiley.com/cms/asset/24f535da-a4ee-442a-b52a-696296d17321/cogs13383-fig-0001-m.jpg