- id: doi:10.3389/fpsyg.2022.1059823
  image: https://www.frontiersin.org/files/Articles/1059823/fpsyg-13-1059823-HTML-r3/image_m/fpsyg-13-1059823-g001.jpg

- title: Can Syntactic Log-Odds Ratio Predict Acceptability and Satiation?
  authors:
    - Jiayi Lu
    - Jonathan Merchan
    - Lian Wang
    - Judith Degen
  publisher: Proceedings of the Society for Computation in Linguistics
  date: 2024-01-01
  link: https://aclanthology.org/2024.scil-1.2/